Реализовать функционал согласно ТЗ 14: хранение данных в postgresql б…
ershovev/java-shareit pull request #2
Opened 2023-07-24 23:43 UTC by Ersh0w

…азе, функционал бронирования вещей, функционал комментариев

2023-07-25 21:04 UTC, sergeymamonov requested changes

2023-07-25 21:04 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingItemDto toBookingItemDto(Optional<Booking> booking) {
Не совсем подходящее использование Optional в качестве аргумента метода. https://struchkov.dev/blog/ru/optional-in-java/#%D0%BA%D0%B0%D0%BA-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0

2023-07-25 21:04 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
>  }
Лучше еще сделать обработку необрабатываемых исключений

2023-07-25 21:05 UTC, sergeymamonov commented
В качестве предложения для улучшения можно сделать классы dto неизменяемыми.

2023-07-26 19:34 UTC, Ersh0w commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static BookingItemDto toBookingItemDto(Optional<Booking> booking) {
Исправлено.

2023-07-26 21:36 UTC, Ersh0w commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
>  }
Исправлено.

2023-07-26 21:37 UTC, Ersh0w commented
> В качестве предложения для улучшения можно сделать классы dto неизменяемыми.

Постараюсь реализовать к следующим ТЗ.

2023-07-27 21:01 UTC, sergeymamonov approved these changes

2023-07-29 11:08 UTC, merged