Реализовать требования ТЗ 15. Функционал запросов вещей и пагинацию. Реализовать тесты.
ershovev/java-shareit pull request #3
Opened 2023-08-04 22:04 UTC by Ersh0w

2023-08-06 04:37 UTC, sergeymamonov requested changes
Для типобезопасности в тестах при использовании MockedStatic лучше указывать принимаемый класс, так как MockedStatic параметризованный интерфейс

2023-08-06 04:37 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void getBookingsOfItemsOwner_shouldBeFound_case_WAITING() {
Этот тест и тест ниже отличаются только в одном параметре. А это значит, что эти два теста можно объединить в один. https://reflectoring.io/tutorial-junit5-parameterized-tests/ Но не настаиваю на этом изменении, а как вариант для улучшения.

2023-08-06 04:37 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertEquals(1, result.size());
Блок проверок схож с блоком проверок в следующем тесте. Значит этот блок кода лучше не повторять дважды, а можно вынести в один метод.

2023-08-06 13:06 UTC, Ersh0w commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void getBookingsOfItemsOwner_shouldBeFound_case_WAITING() {
Исправлено.

2023-08-06 13:06 UTC, Ersh0w commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertEquals(1, result.size());
Исправлено.

2023-08-07 04:47 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/item/ItemRepositoryTest.java
> +        assertEquals(1, result.size());
В тестах если поискать, то можно еще выделить общие куски кода, которые дублируются, и которые можно вынести в отдельные методы. Но ок, этот рефакторинг, на ваше желание.

2023-08-07 04:49 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void getBookingsOfItemsOwner_shouldBeFound_case_WAITING() {
Можно посмотреть и другие тесты, среди них тоже можно выделить схожие и свести их к параметризированным.

2023-08-07 04:50 UTC, sergeymamonov approved these changes

2023-08-07 10:34 UTC, merged