Реализовать ТЗ 16. Реализовать многомодульность и запуск проекта и ба…
ershovev/java-shareit pull request #4
Opened 2023-08-11 18:42 UTC by Ersh0w

…зы данных в докере.

2023-08-12 08:46 UTC, sergeymamonov requested changes
В основном сервисе валидация входных параметров уже не требуется, например аннотации типа @PositiveOrZero, или в методе saveNewBooking валидация дат.

В сервисе gateway в ErrorHandler лучше еще сделать обработку RuntimeException.

2023-08-12 08:46 UTC, sergeymamonov commented on pom.xml
>  	<dependencies>
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию.

2023-08-12 15:53 UTC, Ersh0w commented on pom.xml
>  	<dependencies>
Исправлено.

2023-08-13 09:58 UTC, sergeymamonov approved these changes

2023-09-06 11:37 UTC, merged